# Generated by Django 5.0.6 on 2024-11-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('department', models.CharField(blank=True, choices=[('HR', 'HR'), ('Engineer', 'Engineer'), ('Sales', 'Sales')], max_length=20, null=True)),
                ('role', models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Developer', 'Developer'), ('Analyst', 'Analyst')], max_length=20, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(null=True)),
            ],
        ),
    ]
