# Generated by Django 5.0.6 on 2024-11-04 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_employee_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
    ]
